# Generated by Django 3.0.1 on 2020-01-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_content',
            field=models.TextField(default='lorem ipsum'),
        ),
    ]
